@baseUrl = http://localhost:3001
@json = Content-Type: application/json

###
# Health check
GET {{baseUrl}}

###
# @name login
POST {{baseUrl}}/auth/login
Content-Type: application/json

{
  "email": "admin@example.com",
  "password": "password123"
}

###

###
# Get current authenticated user
GET {{baseUrl}}/auth/me
Authorization: Bearer {{login.response.body.$.access_token}}

###
# =========================
# USERS
# Admin only
# =========================

###
# Get all users
GET {{baseUrl}}/users
Authorization: Bearer {{login.response.body.$.access_token}}

###
# Get one user
GET {{baseUrl}}/users/2
Authorization: Bearer {{login.response.body.$.access_token}}

###
# Create user
POST {{baseUrl}}/users
Authorization: Bearer {{login.response.body.$.access_token}}
{{json}}

{
  "email": "manager1@example.com",
  "password": "password123",
  "role": "manager"
}

###
# Update user
PATCH {{baseUrl}}/users/3
Authorization: Bearer {{login.response.body.$.access_token}}
{{json}}

{
  "email": "manager1@example.com",
  "role": "manager"
}

###
# Delete user
DELETE {{baseUrl}}/users/2
Authorization: Bearer {{login.response.body.$.access_token}}

###
# =========================
# RESIDENTS
# Admin or Manager
# =========================

###
# Get all residents
GET {{baseUrl}}/residents
Authorization: Bearer {{login.response.body.$.access_token}}

###
# Get one resident
GET {{baseUrl}}/residents/1
Authorization: Bearer {{login.response.body.$.access_token}}

###
# Create resident
POST {{baseUrl}}/residents
Authorization: Bearer {{login.response.body.$.access_token}}
{{json}}

{
  "first_name": "Json",
  "last_name": "Therulo",
  "department": "Nuclear Physics"
}

###
# Update resident
PATCH {{baseUrl}}/residents/1
Authorization: Bearer {{login.response.body.$.access_token}}
{{json}}

{
  "department": "science"
}

###
# Delete resident
DELETE {{baseUrl}}/residents/1
Authorization: Bearer {{login.response.body.$.access_token}}

###
# =========================
# ROOMS
# Admin or Manager
# =========================

###
# Get all rooms
GET {{baseUrl}}/rooms
Authorization: Bearer {{login.response.body.$.access_token}}

###
# Get available rooms
GET {{baseUrl}}/rooms/available
Authorization: Bearer {{login.response.body.$.access_token}}

###
# Get one room
GET {{baseUrl}}/rooms/1
Authorization: Bearer {{login.response.body.$.access_token}}

###
# Create room
POST {{baseUrl}}/rooms
Authorization: Bearer {{login.response.body.$.access_token}}
{{json}}

{
  "room_number": 101,
  "floor_number": 1,
  "num_of_beds": 2,
  "id_category": 1
}

###
# Update room
PATCH {{baseUrl}}/rooms/1
Authorization: Bearer {{login.response.body.$.access_token}}
{{json}}

{
  "num_of_beds": 3
}

###
# Delete room
DELETE {{baseUrl}}/rooms/1
Authorization: Bearer {{login.response.body.$.access_token}}